ODIM-Project/ODIM

lib-utilities/common/constants.go
PR is for checklist `Update the Event struct in lib-utilities` in #107 
In this pr below changes are addressed 
1. OriginOfCondition type changed from string to Link object
2. Oem changed from Oem object to interface to support the multiple attributes of Oem
=> odim 107:Updating the Event struct of lib-utilities 

lib-utilities/config/mockconfig.go, lib-utilities/config/mockconfig_test.go
As part of this task   `Add stub connection method in the mock config of lib-utilities` of #173 is completed
=> odim 3617:adding the stub connection methods in config 

svc-api/handle/handlers.go
Updated the ODIM/svc-api/handle/handlers.go with the below lines to change the Content-Type: application/xml.
var headers = map[string]string
{ "Allow": "GET", "Cache-Control": "no-cache", "Transfer-Encoding": "chunked", "Content-type": "application/xml; charset=utf-8",  }
xmlData,_:=xml.Marshal(Metadata)
SetResponseHeaders(ctx, headers)
ctx.Write(xmlData)
=> changes to content-type to application/xml

build/RFPlugin/edit_config.sh, build/odimra/edit_config.sh, lib-messagebus/platforms/platformconfig.toml, plugin-redfish/go.mod, plugin-redfish/go.sum, svc-aggregation/go.mod, svc-aggregation/go.sum, svc-events/go.mod, svc-events/go.sum, svc-task/go.mod, svc-task/go.sum
As part of this pr changes related   `Update the lastest references of the lib-message-bus in ODIM services(svc-aggregation,svc-task and svc-event) and plugin-redfish`  and  `Update the docker-compose to populate platform config.toml with lastest configuration format ` tasks are completed for #241
=> Odim 241:Updating the go.mod reference with latest message bus and edit config.sh for accepting multiple kafka servers

svc-events/events/getevtsubscription.go, svc-events/events/getevtsubscription_test.go
Changes done as part of this PR:
- changed error response for GET operation on invalid event subscription ID, from 400 to 404 
- changed unit test according to the corrected error response
resolves #281
=> ODIM 281: Changed error response status code for GET operation on invalid event subscription ID

svc-events/events/deletesubscription.go, svc-events/events/evtsubscription.go
As part of this PR below changes are done and issue: https://github.com/ODIM-Project/ODIM/issues/227 is addressed 
1.  Logic to handle fqdn with port as hostname while subscribing to event by splitting Fqdn and Port.
2.  Added changes in eventsubscription.go and deletesubscription.go files
3.  Added test case in svc-events
resolves: https://github.com/ODIM-Project/ODIM/issues/227
=> ODIM  227 : svc-events:evtsubscription: failing if port number specified. 

install/Docker/dockerfiles/scripts/consul-entrypoint.sh
Consul entry point script used for starting consul service in container checks if IS_CONSUL_CLUSTER is set to enable consul cluster, which should be case insensitive match of the value.
=> issue-352 : Perform case insensitive match for IS_CONSUL_CLUSTER

svc-api/router/router.go
The PR contains the change for adding the route for doing a patch on the fabric port.
closes #362
=> Issue 362: Route missing for PATCHing fabric port

install/Docker/dockerfiles/scripts/consul-entrypoint.sh, install/Docker/dockerfiles/scripts/start_account_session.sh, install/Docker/dockerfiles/scripts/start_aggregation.sh, install/Docker/dockerfiles/scripts/start_api.sh, install/Docker/dockerfiles/scripts/start_events.sh, install/Docker/dockerfiles/scripts/start_fabrics.sh, install/Docker/dockerfiles/scripts/start_grfplugin.sh, install/Docker/dockerfiles/scripts/start_managers.sh, install/Docker/dockerfiles/scripts/start_systems.sh, install/Docker/dockerfiles/scripts/start_task.sh, install/Docker/dockerfiles/scripts/start_update.sh
Below changes are made in this PR
- Check for count of required process inside container should be equal to 1
- Check for the pgrep command execution result code.
- Send sigterm to main process from the monitoring child process created for graceful exit.
- Perform case insensitive match for HA_ENABLED config.
Resolves: #375
=> issue-375 : monitor and exit when odim-ra process is not running

svc-update/update/getresources.go, svc-update/update/getresources_test.go, svc-update/uresponse/updateservice.go
This PR contains the following fixes
closes #448
=> Odim 448: Semantic fixes on update service

svc-systems/systems/getresource.go, svc-systems/systems/getresource_test.go
Trailing "/" has to be removed from odata.id ("/redfish/v1/Systems/") as per Redfish.Uri standard mentioned in ComputerSystemCollection schema.
=> Issue-463 remove trailing slash in system collection uri @odata.id

svc-aggregation/agresponse/rpc.go
Removed ActionInfo from Action struct in svc-aggregation.
As per the latest Aggregation schema, this is not included.
Resolves https://github.com/ODIM-Project/ODIM/issues/461
=> Odim 461: removed ActionInfo from Action struct

svc-aggregation/agcommon/common.go
The PR contains the fix for connection method update according to the config file changes.
Scenario: We were using a channel called `eventChan` for alerting the AddConnectionMethods function regarding the change in the config file. The message will be put into the channel from the lib-utilities function `TrackConfigFileChanges`.
Issue Found: The current implementation was having an issue that the messages from eventChan were only considered once. So the AddConnectionMethods function will be aware of only the first change that happened in the config file, the rest of the messages in the channel are not received by AddConnectionMethods.
Proposed Solution: We can add an infinite `for loop` which has the channel receiver in it so that AddConnectionMethods will be informed about all the …
=> [Issue-499] Fix for Adding a new connection method in kube_deploy_nodes.yaml after editing and deleting it doesn't get reflected in ODIM

lib-utilities/common/mockconfig.go, lib-utilities/config/README.md, lib-utilities/config/config.go, lib-utilities/config/config_test.go, lib-utilities/config/constants.go, lib-utilities/config/mockconfig.go, lib-utilities/config/odimra_config.json, odim-controller/helmcharts/odimra-config/templates/configmaps.yaml, svc-aggregation/agmessagebus/publish.go, svc-aggregation/agmodel/system.go, svc-aggregation/rpc/aggregator_test.go, svc-aggregation/system/addaggregationsource_test.go, svc-aggregation/system/addcompute.go, svc-aggregation/system/addcompute_test.go, svc-aggregation/system/addplugin_test.go, svc-aggregation/system/common.go, svc-aggregation/system/deleteaggregationsource.go, svc-aggregation/system/rediscoverinventory.go, svc-systems/scommon/common.go, svc-update/ucommon/common.go
Resolved the issue - A Get on a added dell server manager URL containing the ODIM generated UUID was returning 404 Not Found error instead of 200 OK
Even in the manager collection, the manager id for Dell server manager was not having UUID. Resolved this
The issue was if a system id and manager id is different then manager was giving 404, now handled this for any manager id
Resolved the issue - Chassis was showing duplicate resources when using dell plugin
Resolved the issue - Chassis and Manager resource where not getting deleted when a delete server is performed
=> Resolved the managers/chassis issue - a get on BMC manager was giving 404 error and delete server was not deleting the manager and chassis info

README.md
Removed all instances of Lenovo from the Getting Started Readme on upstream dev branch as requested by the team.
=> Remove Lenovo instances from the main getting started readme

lib-dmtf/model/networkport.go
**Changes**
- Added struct for NetworkPort in lib-dmtf as compatible to redfish schema
=> BRUCE-5702-Service validator: "Settings" property in 'NetworkPort' schema is not redfish valid property

docs/README.md
Added heading level 2 for LicenseService section in toc in API readme. This was missed earlier.
=> Added heading level 2 for LicenseService section in toc

lib-dmtf/model/storage.go
Add omitempty for odatatype in storage controller struct
=> odim-6497: Add omitempty for odatatype in storage controller struct

lib-dmtf/model/port.go
Modify datatype for location under Port struct
=> odim-6496: Modify datatype for location under Port struct

build/Redis/6379.conf, build/Redis/6380.conf, install/Docker/dockerfiles/scripts/redis-master.conf, install/Docker/dockerfiles/scripts/redis-slave.conf, odim-controller/helmcharts/redis-ha/values.yaml
Fixes for DB sync issue
Changed the client-output-buffer-limit
Changed the sentinel configuration values
=> Sprint-63-odim-6794: Redis DB Sync issue Fixed 

docs/README.md
- Updated phase 6 downstream content in phase 7 upstream docs (response codes) to be in sync
- Fixed minor consistency in rewording header for SecureBoot APIs because this was a separate PR, other than the PR where consistency issues were fixed.
- Added a header for the "Transfer Protocol" table.
- Updated response code for editing BMC account
=> Updated phase 6 downstream content in phase 7 upstream docs to be in sync + minor fixes
