- svc-aggregation/go.mod
- svc-aggregation/go.sum
- svc-aggregation/rpc/aggregator.go
- svc-api/go.mod
- svc-api/go.sum
Adding the empty signature for new RPC methods of AggregationSource
> Odim 8:Adding the empty signature for new RPCmethods of AggregationSource 

- svc-aggregation/agmodel/system.go
- svc-aggregation/agmodel/system_test.go
- svc-aggregation/rpc/aggregator.go
- svc-aggregation/rpc/aggregator_test.go
- svc-aggregation/system/addaggregationsource.go
- svc-aggregation/system/addplugin.go
- svc-aggregation/system/common.go
- svc-aggregation/system/deleteaggregationsource.go
- svc-aggregation/system/deleteaggregationsource_test.go
- svc-aggregation/system/deletecompute.go
- svc-aggregation/system/deletecompute_test.go
- svc-aggregation/system/get_resource.go
- svc-aggregation/system/get_resource_test.go
- svc-aggregation/system/reset_test.go
- svc-aggregation/system/update.go
- svc-aggregation/system/update_test.go
- svc-api/handle/aggregator.go
- svc-api/handle/aggregator_test.go
- svc-api/router/router.go
- svc-api/rpc/aggregator.go
> Odim 8:Aggregation Source  Get,Update and Delete Operation 

- lib-utilities/response/errorresponse.go
- lib-utilities/response/errorresponse_test.go
- lib-utilities/response/response.go
This PR will resolve one of the checklists of #52
> ODIM-52 add PropertyValueConflict response status message in error response

- svc-task/thandle/tmonitor.go
> odim 55:Updating the subtask link in response

- lib-utilities/common/constants.go
- lib-utilities/common/workerpool.go
- lib-utilities/common/workerpool_test.go
This PR has changes of libutilities changes for get volume #73
> Modification for get volume in constants file

- .github/workflows/build_deploy_test.yml
- build/docker-compose.yml
- plugin-redfish/main.go
- plugin-redfish/rfphandler/update.go
- plugin-redfish/rfphandler/update_test.go
- svc-update/ucommon/common.go
- svc-update/update/getresources_test.go
- svc-update/update/simpleUpdate.go
- svc-update/update/simpleUpdate_test.go
This PR contains the following changes.
- SimpleUpdate Action implementation in update service
- SimpleUpdate Action implementation in plugin
- Deployment of update service fix.
resolves #33
> Odim 33: SimpleUpdate Action implementation 

- svc-api/handle/handlers_test.go
- svc-api/router/router.go
This is PR to Implement retrieval of logical drive using storage schema:
- Implement GET on Volumes collection : Added endpoint in routers for Get Volumes 
closes #73
> Odim 73 : Get Volume collection

- svc-systems/rpc/systems_test.go
- svc-systems/smodel/systems.go
- svc-systems/smodel/systems_test.go
- svc-systems/systems/storage.go
- svc-systems/systems/storage_test.go
This PR is for the issue ` Get on volume is giving success after delete volume `
- Delete volume from DB
> ODIM-127 Get on deleted volume is getting success

- svc-aggregation/system/common.go
- svc-aggregation/system/rediscoverinventory.go
- svc-aggregation/system/rediscoverinventory_test.go
- svc-systems/systems/getresource.go
Implemented refresh storage data in DB, If a storage resource is missing in ODIMRA and present in device
Modified code in svc-aggregation and svc-systems
Resolves #129
> Odim 129 - Implemented refresh storage data in DB 

- svc-systems/systems/bootorder.go
- svc-systems/systems/bootorder_test.go
- svc-systems/systems/getresource.go
- svc-systems/systems/getresource_test.go
- svc-systems/systems/reset.go
- svc-systems/systems/reset_test.go
- svc-systems/systems/storage.go
- svc-systems/systems/storage_test.go
As part of this status code sent for invalid system id  is changed from 400 to 404 
resolves #163
> odm 163:Updating the status code for invalid system id  

- lib-utilities/config/mockconfig.go
- lib-utilities/config/mockconfig_test.go
- svc-aggregation/agcommon/common.go
- svc-aggregation/agcommon/common_test.go
- svc-aggregation/go.mod
- svc-aggregation/go.sum
- svc-aggregation/main.go
> Odim 173:Adding file observer in aggregation service to reload config data

- svc-aggregation/agmodel/system.go
- svc-aggregation/main.go
- svc-aggregation/rpc/common.go
- svc-aggregation/system/addplugin.go
- svc-aggregation/system/addplugin_test.go
- svc-aggregation/system/common.go
> Odim-105 Adding Plugin with duplicate manager address is getting accepted

- svc-events/events/deletesubscription.go
- svc-events/events/evtsubscription.go
- svc-events/events/getevtsubscription_test.go
- svc-events/events/publishevttosubscriber.go
- svc-events/events/publishevttosubscriber_test.go
As part of this PR, the event forwarding issue for fabric resources  is fixed
resolves #192
> issue 192:Updating ip in place fqdn for  create and delete subscription 

- svc-aggregation/agmodel/system.go
- svc-aggregation/rpc/common.go
- svc-aggregation/system/addplugin.go
- svc-aggregation/system/addplugin_test.go
- svc-aggregation/system/common.go
- svc-aggregation/system/deleteaggregationsource.go
closes #208 
The PR contains code for publishing event for ResourceRemoved on Chassis at the time of BMC delete.
The PR also contains code clean up and alignment correction mandated by the go tools.
> fix for Issue 208

- svc-systems/systems/storage.go
As part  this pr in the creation and deletion of a volume if the resource info is not found the ODIMRA database query it from respective BMC and store the info and continue the operation
resolves #214
> odim 214:Adding the loggic get data from device

- svc-aggregation/system/aggregate.go
> ODIM-218 Corrected message and message id in the response for Aggregate.RemoveElements action

- plugin-redfish/main.go
- svc-api/handle/handlers.go
- svc-api/router/router.go
- svc-systems/chassis/getresource.go
- svc-systems/chassis/getresource_test.go
Changes done as part of this PR:
- added route to individual network adapters
- updated metadata with network adapter
- added unit test cases for network adapter
resolves #189
> ODIM 189: Adding Network adapters changes

- .github/workflows/build_deploy_test.yml
- Makefile
- README.md
- build/Kafka/Dockerfiles/Dockerfile.kafka
- build/Kafka/Dockerfiles/Dockerfile.zookeeper
- build/Kafka/scripts/setup_kafka.sh
- build/Kafka/scripts/setup_zookeeper.sh
- build/Kafka/scripts/start_kafka.sh
- build/Kafka/scripts/start_zookeeper.sh
- build/cert_generator/copy_certificate.sh
- build/cert_generator/generate_kafka_certs.sh
- build/cert_generator/generate_zookeeper_certs.sh
- build/cleanupbuild.sh
- build/deepcleanupbuild.sh
- build/docker-compose.yml
- build/run_pre_reqs.sh
Replaced bitnami Kafka & Zookeeper with in house dockerfile.
Made changes to docker-compose to pick  images build from dockerfile.
resolves #228
> Replace Bitnami's Kafka & Zookeeper with the in house developed dockerfile

- svc-task/tmessagebus/publish.go
As part of this pr log message printed  during publishing, the task event is updated 
resolves #224
> odim 224:Updating log  message during publishing the task event  

- plugin-redfish/rfphandler/subscribeEvents.go
- plugin-redfish/rfpresponse/errorResponse.go
As part of this  PR response header formation for event subscription in  GRF plugin is updated 
resolves #226
> Odim 226:Updating response header the formation for event subscription GRF plugin 

- lib-messagebus/datacommunicator/config.go
- lib-messagebus/datacommunicator/config_test.go
- lib-messagebus/datacommunicator/kafkacomm.go
- lib-messagebus/datacommunicator/kafkacomm_test.go
- lib-messagebus/platforms/platformconfig.toml
As part of this pr ` Update lib-message-bus code to accept multiple Kafka host from the configuration`  task of #241  is completed
> Odim 241 task1:Updating the lib-message-bus code to accept multiple kafka host 

- svc-update/main.go
- svc-update/rpc/common.go
- svc-update/rpc/update.go
- svc-update/ucommon/common.go
- svc-update/umodel/update.go
- svc-update/update/getresources.go
- svc-update/update/simpleUpdate.go
- svc-update/update/startUpdate.go
refer https://github.com/ODIM-Project/ODIM/issues/259
This merge request is for svc-update code
> Issue #259 migrate logging to logrus(svc-update)

- svc-events/events/publishevttosubscriber.go
> Odim 266 - Added rediscovery for ResourceAdded/ResourceRemoved events for a volume origin of condition

- README.md
Added details of workflow being executed as checks whenever a PR is raised.
resolved #277
> Issue 277 - Adding of CI process in README.md file

- svc-events/events/publishevttosubscriber.go
- svc-events/events/publishevttosubscriber_test.go
- svc-events/events/submittestevent.go
This PR is for the Release_21.01 branch
> ODIM-320 publish only standard events to NB client

- lib-utilities/etc/Base.1.7.0.json
- lib-utilities/etc/Base.1.8.0.json
- lib-utilities/etc/Base.1.8.1.json
- lib-utilities/etc/Base.1.8.2.json
- lib-utilities/etc/Composition.1.0.1.json
- lib-utilities/etc/JobEvent.1.0.0.json
- lib-utilities/etc/LogService.1.0.0.json
- lib-utilities/etc/NetworkDevice.1.0.0.json
- lib-utilities/etc/NetworkDevice.1.0.1.json
- lib-utilities/etc/Redfish_1.1.0_PrivilegeRegistry.json
- lib-utilities/etc/ResourceEvent.1.0.3.json
- lib-utilities/etc/StorageDevice.1.0.0.json
- lib-utilities/etc/TaskEvent.1.0.2.json
- svc-events/events/publishevttosubscriber.go
- svc-events/events/publishevttosubscriber_test.go
- svc-events/events/submittestevent.go
this PR is for Release_21.01 branch
> ODIM-322 Update latest Message registry files in Release_21.01 branch

- plugin-unmanaged-racks/redfish/events.go
- plugin-unmanaged-racks/rest/events_listener.go
- plugin-unmanaged-racks/rest/module_test.go
> Issue-343 Change type of OriginOfCondition from string to Object in URP in Release_21.01 branch

- build/Kafka/Dockerfiles/Dockerfile.kafka
- build/Kafka/Dockerfiles/Dockerfile.zookeeper
- lib-rest-client/pmbhandle/rest.go
- lib-utilities/common/pluginstatus.go
- lib-utilities/config/httpConfig.go
- plugin-redfish/rfputilities/redfishClient.go
- svc-events/evcommon/common.go
- svc-events/events/publishevttosubscriber.go
As part of this pr changes related to #360  are added
> odim 310:Adding all changes related to the race condition fix to the release branch

- build/Kafka/Dockerfiles/Dockerfile.kafka
- build/Kafka/Dockerfiles/Dockerfile.zookeeper
- lib-rest-client/pmbhandle/rest.go
- lib-utilities/common/pluginstatus.go
- lib-utilities/config/httpConfig.go
- plugin-redfish/rfputilities/redfishClient.go
- svc-events/evcommon/common.go
- svc-events/events/publishevttosubscriber.go
> Revert "odim 310:Adding all changes related to the race condition fix to the release branch"

- svc-aggregation/system/addaggregationsource.go
- svc-aggregation/system/common.go
- svc-aggregation/system/update.go
As part of this pr, the add aggregation source  task response is changed
resolves #377
> Odim 377:Updating the task response in add aggregation source 

- build_images.sh
- install/Docker/dockerfiles/Dockerfile.odim
- install/Docker/dockerfiles/Dockerfile.urplugin
- install/Docker/dockerfiles/scripts/start_urplugin.sh
> Added URP deploy script, docker file and removed plugin-redfish binary

- lib-dmtf/model/ComputerSystem.go
- lib-dmtf/model/Links.go
- lib-dmtf/model/addressPool.go
- lib-dmtf/model/common.go
- lib-dmtf/model/fabric.go
- lib-dmtf/model/manager.go
- lib-dmtf/model/resourceCollection.go
- lib-dmtf/model/switch.go
As part  of this pr the  fabric, switch, collection, and manager models are added 
closes #400
> odim 400:Adding the fabric ,switch ,collection and manager model 

- lib-dmtf/model/Chassis.go
- lib-dmtf/model/addressPool.go
- lib-dmtf/model/fabric.go
- lib-dmtf/model/manager.go
- lib-dmtf/model/switch.go
As part of this pr  id reference in the fabric, switch, manager, and address pool of  dmtf model is updated 
closes #414
> odim 414:Updating the id reference in the fabric, switch ,manager and address pool dmtf model

- svc-systems/chassis/fabric.go
- svc-systems/chassis/fabric_test.go
- svc-systems/chassis/fabricresource.go
- svc-systems/chassis/update.go
- svc-systems/chassis/updatefabricresource.go
- svc-systems/chassis/updatefabricresource_test.go
The PR contains the PATCH on fabric chassis
The PR is the fix for task 4 #390
> Issue 390 task 4: Modify the PATCH on individual device chassis resource for newly added fabric chassis resources

- lib-persistence-manager/persistencemgr/redis.go
- svc-aggregation/agmodel/system.go
- svc-task/tmodel/tmodel.go
adding logs to task.go, system.go and redis.go  files
Resolves : https://github.com/ODIM-Project/ODIM/issues/428
> adding logs to task.go, system.go and redis.go  files

- lib-dmtf/model/port.go
As part of this pr Port model is added lib-dmtf package 
closes #432
> odim 432:Adding Port model to lib-dmtf package 

- lib-persistence-manager/persistencemgr/redis.go
- odim-controller/helmcharts/redis-ha/values.yaml
Code changes for Redis master pod reset: adding retry logic
closes #348
> Issue 348- Adding server failed after master redis pod reset

- odim-controller/odimra/deploy_plugin.yaml
- odim-controller/odimra/roles/deploy-plugin/tasks/main.yaml
- odim-controller/odimra/roles/remove-plugin/tasks/main.yaml
- odim-controller/odimra/roles/upgrade-config/tasks/main.yaml
- odim-controller/odimra/roles/upgrade-thirdparty/tasks/main.yaml
- odim-controller/odimra/upgrade_plugin.yaml
- odim-controller/scripts/odim-controller.py
PR contains below changes
- Changed the function and role names used for deploying plugin.
- Changed logs generated during plugin deployment
> issue-438 : Update log messages during plugin add and upgrade operation

- odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
> updated default redis configurations

- lib-utilities/common/constants.go
- svc-api/handle/chassis.go
Update the api service to handle the network adapter ports and network device functions resources
closes #457
> Fix on Chassis resources GET

- lib-utilities/config/httpConfig.go
- lib-utilities/config/httpConfig_test.go
- plugin-unmanaged-racks/rest/get_chassis_collection_handler.go
- plugin-unmanaged-racks/rest/patch_chassis_handler.go
- svc-fabrics/fabrics/common.go
- svc-systems/plugin/client.go
PR changes contain:
- Changed from asserting response body string to converting the response body content to string.
- Reinitialize http client object with tlsconfig only when it's nil
Resolves: #459
> issue-459 : Patch request to attach system chassis to Rack is failing

- lib-dmtf/model/common.go
- lib-dmtf/model/storage.go
- update storage object with pointer
- remove omitempty in LocationOrdinalValue, if it has 0 value then it will not display in storage object
> Issue-470 update storage object with pointer

- svc-fabrics/fabrics/addfabric.go
> issue-486 : Check both IP address and servicename/FQDN in events to identify the fabric plugin

- svc-api/handle/chassis.go
- svc-api/handle/handlers.go
- svc-api/router/router.go
- svc-api/rpc/chassis.go
> Odim 507:Updating the routes of message registries 

- plugin-dell/config/config.go
- plugin-dell/dphandler/basicAuth.go
- plugin-dell/dphandler/biosSettings.go
- plugin-dell/dphandler/biosSettings_test.go
- plugin-dell/dphandler/bootorder.go
- plugin-dell/dphandler/common.go
- plugin-dell/dphandler/createSession.go
- plugin-dell/dphandler/getResource.go
- plugin-dell/dphandler/managers.go
- plugin-dell/dphandler/pluginStatus.go
- plugin-dell/dphandler/redfishEvents.go
- plugin-dell/dphandler/reset.go
- plugin-dell/dphandler/storage.go
- plugin-dell/dphandler/subscribeEvents.go
- plugin-dell/dphandler/update.go
- plugin-dell/dpmessagebus/publish.go
- plugin-dell/dpmiddleware/basicAuthenticate.go
- plugin-dell/dputilities/redfishClient.go
- plugin-dell/dputilities/utility.go
- plugin-dell/go.mod
- plugin-dell/main.go
PR contains:
- correction in main package
- correction in config package
- correction in rfphandler package
- correction in rfpmessagebus package
- correction in rfpmiddleware package
- correction in rfputilities package
closes #514
> Issue 514: Make use of logrus package in DELL plugin for logging

- lib-dmtf/model/Chassis.go
- lib-dmtf/model/power.go
> odim 506:Adding power model to lib-dmtf

- lib-dmtf/model/Chassis.go
- lib-dmtf/model/thermal.go
> odim 520:Adding the thermal model to lib-dmtf

- svc-task/thandle/thandle.go
- svc-task/tmodel/tmodel.go
- svc-task/tmodel/tmodel_test.go
> odim 525:Updating the completed task index for the task which is having task state as Exception 

- svc-events/events/deletesubscription.go
> odim 526:Adding the condition to check  plugin service name in device subscription 

- lib-dmtf/model/ComputerSystem.go
> Issue 533: Correct BIOS schema to lib-dmtf

- lib-utilities/config/odimra_config.json
- lib-utilities/services/name.go
- odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
- svc-api/go.mod
- svc-api/handle/handlers.go
- svc-api/handle/telemetry.go
- svc-api/handle/telemetry_test.go
- svc-api/models/serviceroot.go
- svc-api/router/router.go
- svc-api/rpc/telemetry.go
* handlers for telemetry service and resources
* telemetry service under api service
* telemetry service name added to odim config
closes #534
> Telemetry service implementation under api service and lib-utilities

- odim-controller/odimra/pre_upgrade.yaml
- odim-controller/odimra/roles/pre-upgrade/tasks/main.yaml
- odim-controller/scripts/odim-controller.py
> issue-546 : fix for copying docker images during upgrade

- plugin-dell/dphandler/storage.go
- plugin-dell/dphandler/storage_test.go
- plugin-dell/dpmodel/storage.go
* Added the validations for firmware check of dell server and the payload is standardized as per new firmware version 4.40
* Ran go tools and updated UT
* Resolves #548
> Updated the payload for create volume as per 4.40 firmware version of Dell server

- .github/workflows/build_deploy_test.yml
- .github/workflows/build_unittest.yml
- Makefile
- build/LenovoPlugin/Dockerfile.lenovo_plugin
- build/LenovoPlugin/command.sh
- build/LenovoPlugin/edit_config.sh
- build/LenovoPlugin/lenovo_plugin.service
- build/LenovoPlugin/start_plugin.sh
- build/cleanupbuild.sh
- build/deepcleanupbuild.sh
- build/docker-compose.yml
- build/odimra/Dockerfile.odimra
- build_images.sh
- install/Docker/dockerfiles/Dockerfile.lenovoplugin
- install/Docker/dockerfiles/Dockerfile.odim
- install/Docker/dockerfiles/scripts/start_lenovoplugin.sh
- odim-controller/helmcharts/lenovoplugin/lenovoplugin-config.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/Chart.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/_helpers.tpl
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/configmaps.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/deployment.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/pv.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/pvc.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/templates/service.yaml
- odim-controller/helmcharts/lenovoplugin/lenovoplugin/values.yaml
- plugin-lenovo/config/config.go
- plugin-lenovo/config/lenovo_config.json
- plugin-lenovo/config/mockconfig.go
Adding the deployment files and helm charts for plugin Lenovo
This PR will close #554
> Adding deployment files and helm charts for Lenovo plugin

- lib-dmtf/model/telemetry.go
This PR is raised for telemetry feature branch
> ODIM-573 Correct MetricReports model in lib-dmtf

- plugin-redfish/main.go
- svc-aggregation/system/addcompute.go
- svc-aggregation/system/common.go
- svc-api/handle/telemetry.go
- svc-telemetry/telemetry/common.go
- svc-telemetry/telemetry/telemetry.go
Get below metric data from southbound and store it in DB
- MetricDefinitionCollection
- MetricReportDefinitionCollection
- MetricReportCollection
- TriggerCollection
> ODIM-589 Store metric data in db

- plugin-redfish/rfpmessagebus/publish.go
* Forwarding telemetry report event to ODIM with systemID and chassisID replaced
* Seperated event format based on event type
> Forwarding telemetry report event to ODIM (#35)

- svc-telemetry/main.go
This PR contains the following changes 
- API service changes to handle update request
- Handler under telemetry service to handle update request
- Models and dependencies under telemetry service 
- GRF plugin to handle update request
> Update individual Trigger

- lib-dmtf/model/storage.go
- svc-aggregation/system/aggregate.go
Removed extra properties-id,message,messageid and severity from Aggregates collection
Corrected the property name in storage from description to Description
> Removed properties which are not part of AggregateCollection schema

- docs/README.md
* replacing the updated readme with Telemetry section updated
* addressed Shiva's feedback
* fixed formatting in tables
* addressing feedback from Irappa
> Update Telemetry Services Instructions in API Guide (#8)

- docs/README.md
Updated sample responses for all VirtualMedia APIs
> updated sample responses for VirtualMedia APIs

- odim-controller/scripts/odim-controller.py
PR contains changes done for capturing output of odim-controller to a log file
- User can provide desired log filepath by setting ODIM_CONTROLLER_LOG_PATH environment variable
- Log file will be stored as ${ODIM_CONTROLLER_LOG_PATH}/odim-controller.log if variable is set else in the current dir where odim-controller was invoked as ./odim-controller.log
- For every odim-controller invocation, below will be logged
- Start time and end time
- User and the groups user belongs to
- options passed to odim-controller
- and the complete output of the operation
> ODIM-20 : log odim-controller operations and output to a file (#41)

- plugin-lenovo/lphandler/common.go
- plugin-lenovo/lphandler/managers.go
- plugin-lenovo/lphandler/managers_test.go
- plugin-lenovo/lpmodel/managers.go
- plugin-lenovo/main.go
* Added support for insert and eject virtual media
* Added UT for managers
* Ran go tools
> Implemented Insert and Eject VirtualMedia for Lenovo plugin

- lib-dmtf/model/manager.go
- plugin-lenovo/lphandler/getResource.go
* Added actions property in virtualmedia for lenovo plugin
* Ran go tools
> Added actions for get on virtual media (#26)

- docs/README.md
- svc-telemetry/README.md
Updates sample response text for the following TelemetryService APIs in the API readme and in the `svc-telemetry` directory:
- Collection of metric definitions
- Single metric definition
- Collection of Metric Report Definitions
- Single metric report definition
- Collection of metric reports
- Single metric report
- Collection of Triggers
- Single Trigger
> Updating Telemetry Services APIs section and merging to dev upstream

- .github/workflows/odimra_deployment.yml
- lib-dmtf/model/storage.go
- lib-messagebus/datacommunicator/kafkacomm.go
- lib-utilities/common/jobqueue.go
- lib-utilities/common/jobqueue_test.go
- lib-utilities/common/workerpool_test.go
- plugin-dell/main.go
- plugin-lenovo/main.go
- plugin-redfish/main.go
- svc-aggregation/system/pluginHealthCheck.go
- svc-events/consumer/consumer.go
- svc-events/consumer/consumer_test.go
- svc-events/main.go
PR Contains:
- Increase the channel buffer size used for processing events for faster processing of events
- Release slice used in event processing flow
> ODIM-46 : Increase the channel buffer size used for processing events

- svc-aggregation/agmodel/system.go
- svc-aggregation/agmodel/system_test.go
- svc-aggregation/system/addaggregationsource.go
- svc-aggregation/system/addaggregationsource_test.go
- svc-aggregation/system/addcompute.go
- svc-aggregation/system/common.go
- svc-aggregation/system/rediscoverinventory.go
- svc-aggregation/system/reset_test.go
- svc-aggregation/system/systemstate.go
- svc-aggregation/system/update.go
LFN Jira URL 
https://jira.lfnetworking.org/browse/ODIM-56
> Odim 56:Adding Changes related to verifying the BMC address uniqueness

- lib-messagebus/datacommunicator/header.go
- lib-messagebus/datacommunicator/redisstreamcomm.go
- lib-messagebus/go.mod
- lib-messagebus/go.sum
- svc-events/consumer/consumer.go
- svc-events/consumer/consumer_test.go
- svc-events/main.go
LFN Jira URL:https://jira.lfnetworking.org/browse/ODIM-74
> odim 74:Adding changes related to the redis stream event consuming 

- .github/workflows/build_unittest.yml
- install/Docker/dockerfiles/Dockerfile.accountSession
- install/Docker/dockerfiles/Dockerfile.aggregation
- install/Docker/dockerfiles/Dockerfile.api
- install/Docker/dockerfiles/Dockerfile.dellplugin
- install/Docker/dockerfiles/Dockerfile.etcd
- install/Docker/dockerfiles/Dockerfile.events
- install/Docker/dockerfiles/Dockerfile.fabrics
- install/Docker/dockerfiles/Dockerfile.grfplugin
- install/Docker/dockerfiles/Dockerfile.kafka
- install/Docker/dockerfiles/Dockerfile.lenovoplugin
- install/Docker/dockerfiles/Dockerfile.managers
- install/Docker/dockerfiles/Dockerfile.systems
- install/Docker/dockerfiles/Dockerfile.task
- install/Docker/dockerfiles/Dockerfile.telemetry
- install/Docker/dockerfiles/Dockerfile.update
- install/Docker/dockerfiles/Dockerfile.urplugin
- install/Docker/dockerfiles/Dockerfile.zookeeper
LFN Jira URL:https://jira.lfnetworking.org/browse/ODIM-79
> Odim 79:Updating the ubuntu base image

- odim-controller/scripts/go.mod
- odim-controller/scripts/go.sum
Add go.mod file in scripts folder
> odim-5495: Add go.mod file in scripts folder

- lib-messagebus/datacommunicator/config.go
- lib-messagebus/datacommunicator/kafkacomm.go
- lib-messagebus/datacommunicator/redisstreamcomm.go
- odim-controller/helmcharts/odimra-platformconfig/templates/configmaps.yaml
- svc-events/consumer/consumer_test.go
- svc-events/evcommon/common_test.go
- svc-events/evresponse/events.go
LFN JiraURL https://jira.lfnetworking.org/projects/ODIM/issues/ODIM-76
> odim 76:Adding the changes to check kafka configuration in lib-message bus

- svc-managers/mgrmodel/manager.go
ODIM-5533: Fixed Odimra service manager empty @odata.id in the Certificates property
> ODIM-5533: Fixed Odimra service manager empty @odata.id in the Certificates property

- svc-managers/managers/managers.go
- svc-managers/managers/managers_test.go
- svc-managers/mgrmodel/manager.go
Add ManagerForChassis and ManagerForServer links under odim manager
> odim-5454: Add ManagerForChassis ManagerForServer and ManagersForManager links under odim manager

- docs/README.md
- Update Sample Responses for AggregationSources, event subscription and telemetry service as per team's latest feedback
- Add "generating and importing certs section before adding server section as per Sukhwinder's feedback
> Merge to release - Sample responses updated + adding  "generating and importing certs section before adding server section"

- README.md
Merge to release branch - Overall Team's feedback PR
- Pluginpath should not be empty. Ada a note in odim-controller config parameters table!
- Re-arrange steps in "Setting up the environment" section.
- Replace controller nodes with cluster nodes in "Deployment considerations" section.
- Update parameters list for all plugins in step 12 example. (including ACI plugin)
- Specify what is odim_username and odim_password in the section "Adding a plugin into the Resource Aggregator for ODIM framework"
- Remove $ symbols in commands found in lenovo deployment instructions section.
- Update few pkgs version information given along with the example of calico name and version
- Remove hardcoded connectionMethodID in sample payload of all plugins in the section "Adding a plugin into the Resource …
> Merge to release branch - Overall Team's feedback PR

- docs/README.md
- Merge to dev - Update Sample Responses for AggregationSources, event subscription and telemetry service as per team's latest feedback
- Add "generating and importing certs section before adding server section as per Sukhwinder's feedback
> Merge to Dev - Update Sample Responses as per team's feedback + adding "generating and importing certs section before adding server section" 

- lib-dmtf/model/storage.go
Add pointer to the bool parameter
> odim-5732: Add pointer to the bool parameter

- svc-composition-service/app/db/persistant.py
- svc-composition-service/app/rest/composition_service.py
- svc-composition-service/app/rest/pool.py
- svc-composition-service/app/rest/resource_blocks.py
- svc-composition-service/app/rest/resource_zones.py
- svc-composition-service/app/utilities/auth.py
- svc-composition-service/app/utilities/client.py
- svc-composition-service/app/utilities/client_service.py
- svc-composition-service/app/utilities/crypt.py
updated the changes for composition_service as sync with main branch
> updated the changes for composition_service

- .github/workflows/build_unittest.yml
- build/Redis/Dockerfile.redis
- install/Docker/dockerfiles/Dockerfile.redis
- odim-controller/helmcharts/redis-ha/Chart.yaml
- odim-controller/helmcharts/redis/Chart.yaml
- odim-controller/helmcharts/redis/templates/_helpers.tpl
- odim-controller/odimra/group_vars/all/all.yaml
Made redis version changes from 6.2.5 to 6.2.6 in Dockerfiles, Helmcharts.
> ODIM-5797: Upgrade redis from version 6.2.5 to 6.2.6 

- lib-dmtf/model/licenses.go
- lib-utilities/proto/licenses/licenses.proto
- svc-api/handle/handlers.go
- svc-api/handle/licenses.go
- svc-api/handle/licenses_test.go
- svc-api/router/router.go
- svc-api/rpc/licenses.go
- svc-licenses/lcommon/common.go
- svc-licenses/licenses/common_test.go
- svc-licenses/licenses/licenses.go
- svc-licenses/licenses/licenses_test.go
- svc-licenses/model/licenses.go
- svc-licenses/rpc/licenses.go
- svc-licenses/rpc/licenses_test.go
- Implement action under license service
- Changes in ilo plugin
- Add UT's
> Implement action under license service for Systems and Managers resource URLs

- svc-aggregation/agmodel/system.go
- svc-aggregation/agmodel/system_test.go
- svc-aggregation/agresponse/aggregationsource.go
- svc-aggregation/go.mod
- svc-aggregation/go.sum
- svc-aggregation/rpc/aggregator_test.go
- svc-aggregation/system/aggregate.go
- svc-aggregation/system/aggregate_test.go
**Changes**
- Changed the data type of Elements in Aggregate APIs from an array of strings to an array of OdataID.
- Made the enough changes in unit test.
> BRUCE-5743 Aggregates request payload and response is not as per redfish spec 

- odim-controller/scripts/odim-controller.py
Handle odim-controller.lock to resolve deploy/reset issue
> odim-6295: Handle odim-controller.lock to resolve deploy/reset issue

- svc-aggregation/agresponse/aggregationsource.go
- svc-aggregation/system/aggregate.go
- svc-aggregation/system/aggregate_test.go
ODIM supports actions for aggregates and these are currently not part of individual aggregates response body.
Added the actions and elements count.
> Odim-6229 : Added actions and elements count in aggregates response body

- svc-aggregation/agmodel/system.go
Update string separators while add and remove aggregate elements
> Update string separators while add and remove aggregate elements

- svc-aggregation/rpc/aggregator.go
Change DataType value for ResetActionInfo response
> odim-6468: Change DataType value for ResetActionInfo response

- docs/README.md
API readme feedback is merged today. Just 2 minor, last minute updates from Rahul so directly raising it against upstream dev.
> Team feedback on eventservice

- lib-dmtf/model/storage.go
Add omitempty to collectionCapabilities field
> odim-6666: Add omitempty to collectionCapabilities field

- .github/workflows/odimra_deployment.yml
- lib-utilities/config/config.go
- lib-utilities/config/odimra_config.json
- odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
- odim-controller/helmcharts/odimra-config/values.yaml
- odim-controller/scripts/odim-controller.py
ODIM RHOCP deployment is failing due to the missing configurations.
To fix this Added config parameters for imageregistery and fixed issue with loglevel in helm charts
> Odim-6685: Fixed ODIM deployment failing issue due to the missing helm configurations

- .github/workflows/build_unittest.yml
- build_images.sh
- docker-images.sh
- odim-controller/helmcharts/create_helm_packages.sh
- odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
- odim-controller/odimra/group_vars/all/all.yaml
- svc-api/router/router.go
Disable composition service deployment
> odim-6689: Disable composition service deployment

- svc-aggregation/agmodel/system.go
- svc-aggregation/agmodel/system_test.go
- svc-api/models/registries.go
BiosAttribute url not getting listed in RegistryFileCollection
> Bruce-6747: BiosAttribute url not getting listed in RegistryFileCollection

- svc-aggregation/agcommon/common_test.go
Increase the UT coverage for agcommon folder for aggregation service
> odim-6775: Increase the UT coverage for agcommon folder for aggregation service

- README.md
Added Log levels and support for logs in syslog format in GS readme
> Merge to dev - Log levels and support for logs in syslog format

- lib-dmtf/go.mod
- lib-dmtf/go.sum
- lib-persistence-manager/persistencemgr/redis.go
- lib-utilities/common/constants.go
- lib-utilities/common/kubernetes.go
- lib-utilities/common/responses.go
- lib-utilities/logs/logger.go
- svc-api/handle/systems.go
- svc-api/handle/systems_test.go
- svc-api/main.go
- svc-api/router/router.go
- svc-api/rpc/system.go
- svc-api/rpc/system_test.go
- svc-systems/rpc/chassis.go
- svc-systems/rpc/chassis_test.go
- svc-systems/rpc/systems.go
- svc-systems/rpc/systems_test.go
- svc-systems/systems/getresource.go
- svc-systems/systems/getresource_test.go
Add process related logs under system collection
> Bruce-6816: Add process related logs under system collection

- docs/Troubleshooting.md
Removed information that had Docker instances for cluster nodes from the troubleshooting readme
> Removed instances of Docker for cluster nodes

- .github/workflows/build_unittest.yml
- build/Redis/Dockerfile.redis
- install/Docker/dockerfiles/Dockerfile.redis
- install/Docker/dockerfiles/scripts/redis-entrypointsetup.sh
- lib-persistence-manager/persistencemgr/redis.go
- odim-controller/helmcharts/redis-ha/Chart.yaml
- odim-controller/helmcharts/redis/Chart.yaml
- odim-controller/helmcharts/redis/templates/_helpers.tpl
- odim-controller/odimra/group_vars/all/all.yaml
Currently if a Redis master goes down, another master is not coming up.
> Fixed Redis failover issue

- lib-utilities/common/constants.go
- svc-managers/managers/common.go
- svc-managers/managers/common_test.go
- svc-managers/managers/managers.go
- svc-managers/managers/managers_test.go
- svc-managers/mgrcommon/common.go
- svc-managers/mgrcommon/common_test.go
- svc-managers/rpc/manager.go
- svc-managers/rpc/manager_test.go
Add process logs for svc-managers
> Add process logs for svc-managers 

- svc-aggregation/agmodel/system.go
- svc-aggregation/agmodel/system_test.go
Increase UT coverage for svc-aggregation
- agmodel (ok      github.com/ODIM-Project/ODIM/svc-aggregation/agmodel    2.550s  coverage: 74.0% of statements)
> Increase UT coverage for svc-aggregation

- odim-controller/helmcharts/odimra-config/templates/configmaps.yaml
Adding the new config "OdimControlMessageQueue" to the plugin-ilo helm variable
> Adding the new config "OdimControlMessageQueue" to the odimra_config helm chart

- lib-utilities/common/constants.go
- lib-utilities/common/responses.go
- svc-account-session/auth/session.go
- svc-account-session/rpc/sessions.go
- svc-update/rpc/common.go
- svc-update/rpc/update.go
- svc-update/rpc/update_test.go
- svc-update/ucommon/common.go
- svc-update/ucommon/common_test.go
- svc-update/umodel/update.go
- svc-update/update/common.go
- svc-update/update/getresources.go
- svc-update/update/getresources_test.go
- svc-update/update/simpleUpdate.go
- svc-update/update/simpleUpdate_test.go
- svc-update/update/startUpdate.go
- svc-update/update/startUpdate_test.go
Add process logs for Update service
> Add process logs for Update service

- lib-dmtf/model/events.go
Actions for every resource vary, Adding Actions schema for EventDestination resources
> Add EventDestination Actions Schema in lib-dmtf

- README.md
- Added a new section Backup and restore of Redis in the Getting Started Readme
- Replaced instances of /home/bruce throughout the doc appropriately
> Added a new section Backup and restore of Redis

- lib-utilities/logs/logger.go
Adding EventService v1.8.0.json  schema model to lib-dmtf
> Adding EventService Schema model to lib-dmtf

- svc-aggregation/rpc/aggregator.go
- svc-aggregation/system/common.go
- svc-aggregation/system/deleteaggregationsource.go
- svc-aggregation/system/rediscoverinventory.go
Task for delete aggregation not getting updated
> Task for delete aggregation not getting updated

- lib-utilities/common/constants.go
- svc-telemetry/rpc/common.go
- svc-telemetry/rpc/common_test.go
- svc-telemetry/rpc/telemetry.go
- svc-telemetry/rpc/telemetry_test.go
- svc-telemetry/tcommon/common.go
- svc-telemetry/tcommon/common_test.go
- svc-telemetry/telemetry/common.go
- svc-telemetry/telemetry/telemetry.go
- svc-telemetry/telemetry/telemetry_test.go
- svc-telemetry/tmodel/model.go
- svc-telemetry/tmodel/model_test.go
Add all log properties in telemetry service
> Add all log properties in telemetry service

- .github/workflows/codeql.yml
Fixing the code scanning issue for direct logging of the fields
> Fixing the code scanning issue for log fields

- lib-utilities/common/constants.go
- svc-fabrics/fabrics/addfabric.go
- svc-fabrics/fabrics/addfabric_test.go
- svc-fabrics/fabrics/common.go
- svc-fabrics/fabrics/common_test.go
- svc-fabrics/fabrics/createresource.go
- svc-fabrics/fabrics/createresource_test.go
- svc-fabrics/fabrics/deleteresource.go
- svc-fabrics/fabrics/deleteresource_test.go
- svc-fabrics/fabrics/getresource.go
- svc-fabrics/fabrics/getresource_test.go
- svc-fabrics/fabrics/removefabric.go
- svc-fabrics/fabrics/removefabric_test.go
- svc-fabrics/rpc/fabrics.go
- svc-fabrics/rpc/fabrics_test.go
Add all the log properties in fabrics service
> Add all the log properties in fabrics service

- docs/README.md
Updated to latest samples of audit logs, security logs, added sample log in JSON format and added header for log details in API guide as per team's feedback
> Updated samples of audit logs and security logs and added sample log in JSON format

- README.md
updated golang version in gs readme.
> updated golang version

- lib-utilities/logs/logger.go
- lib-utilities/logs/logging.go
- svc-account-session/auth/auth.go
- svc-account-session/auth/session.go
- svc-account-session/role/delete.go
- svc-account-session/role/delete_test.go
- svc-account-session/rpc/account.go
- svc-account-session/rpc/account_test.go
- svc-account-session/rpc/role.go
- svc-account-session/rpc/role_test.go
- svc-account-session/session/getsession.go
- svc-account-session/session/getsession_test.go
Remove session token from logs
> Remove session token from logs

- svc-account-session/auth/session.go
- svc-account-session/session/delete.go
- svc-account-session/session/getsession.go
Remove session tokens from logs
> Remove session tokens from logs

- svc-systems/rpc/systems.go
- svc-systems/rpc/systems_test.go
- svc-systems/systems/storage.go
- svc-systems/systems/storage_test.go
Implement tasks for volume create functionality
> Implement tasks for volume create functionality

- lib-utilities/common/generalerror.go
- svc-systems/rpc/systems.go
- svc-systems/rpc/systems_test.go
- svc-systems/systems/bootorder.go
- svc-systems/systems/bootorder_test.go
- svc-systems/systems/storage.go
Implement tasks for Bios settings
> Implement tasks for Bios settings

- docs/README.md
Fixed incorrect command in updating log levels in API readme
> Fixed incorrect command in updating log levels

- README.md
updated connectionmethod variant versions for dell and lenovo + updated backup restore instructions for Redis
> updated connectionmethod variant versions for dell and lenovo + updated backup restore instructions for Redis

- svc-managers/managers/managers.go
- svc-managers/managers/managers_test.go
- svc-managers/mgrmodel/device.go
- svc-managers/mgrresponse/managers.go
- svc-managers/mgrresponse/rpc.go
- svc-managers/rpc/manager.go
- svc-managers/rpc/manager_test.go
Implement tasks for insert and eject virtual media
> Implement tasks for insert and eject virtual media

- svc-update/update/simpleUpdate.go
- svc-update/update/startUpdate.go
- svc-update/update/startUpdate_test.go
Implemented tasks for update service - start update
> Implemented tasks for update service - start update

- svc-aggregation/main.go
Removing rediscovery resources from aggregation service
> Removing rediscovery resources from aggregation service

- svc-aggregation/system/rediscoverinventory.go
Adding mutex to avoid connection pool blocking
> Adding mutex to avoid connection pool blocking

- install/Docker/dockerfiles/scripts/start_account_session.sh
- install/Docker/dockerfiles/scripts/start_aggregation.sh
- install/Docker/dockerfiles/scripts/start_api.sh
- install/Docker/dockerfiles/scripts/start_dellplugin.sh
- install/Docker/dockerfiles/scripts/start_events.sh
- install/Docker/dockerfiles/scripts/start_fabrics.sh
- install/Docker/dockerfiles/scripts/start_grfplugin.sh
- install/Docker/dockerfiles/scripts/start_licenses.sh
- install/Docker/dockerfiles/scripts/start_managers.sh
- install/Docker/dockerfiles/scripts/start_systems.sh
- install/Docker/dockerfiles/scripts/start_task.sh
- install/Docker/dockerfiles/scripts/start_telemetry.sh
- install/Docker/dockerfiles/scripts/start_update.sh
- install/Docker/dockerfiles/scripts/start_urplugin.sh
Reverts ODIM-Project/ODIM#1198
> Revert "Replacing nohup with tee to print the logs on console too "

- README.md
As per the updates made to Getting Started Guide in Phase 6 release,
Updated commands to install latest third-party packages in "Setting up the environment" section in Getting Started Readme.
> Update commands to install latest third-party packages

- README.md
Added info on the new property logsOnConsole for odim and plugins in the GS readme
> Add info on logsOnConsole for odim and plugins

- docs/README.md
Fixed extra spaces in codeblock, fixed bulleting and broken links in TOC in the API readme
> Fixed extra spaces in codeblock, fixed bulleting and broken links in TOC

- README.md
Updated GitHub action workflow details URL in GSG to reflect the latest Ubuntu version
> Updated GitHub action workflow details URL

- docs/README.md
Changed MessageIDs property to MessageIds as per DMTF Redfish schema in API readme
> Address team feedback for event subscription property in request body
